export const data = {
	exams: [
		{
			name: 'arabic',
			taken: false,
			grade: 0,
			createdBy: '',
			createdAt: new Date(),
			enrolledSutdents: [],
			exam: [
				{
					quizNumber: '1',
					image:
						'https://images.unsplash.com/photo-1616091653488-e80acefedc83?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2134&q=80',
					question: '',
					option1: 'Ferrari',
					option2: 'Nissan',
					option3: 'Ford',
					option4: '',
					answer: 'Ferrari.',
				},
				{
					quizNumber: '2',
					image: '',
					question:
						'In the professional era which woman has won the most titles at Wimbledon [singles, doubles and mixed] ?',
					option1: 'Venus',
					option2: 'Hingis',
					option3: 'Martina Navratilova',
					option4: 'Waynetta',
					answer: 'Martina Navratilova',
				},
				{
					quizNumber: '3',
					image: '',
					question: 'How many times have Liverpool been relegated from the top flight of English football?',
					option1: 'Four',
					option2: 'Three',
					option3: 'Two',
					option4: 'Five',
					answer: 'Three',
				},
			],
		},

		{
			name: 'math',
			taken: false,
			grade: 0,
			createdBy: '',
			createdAt: new Date(),
			enrolledSutdents: [],
			exam: [
				{
					quizNumber: '1',
					image: '',
					question: 'What is the scientific name of a butterfly?',
					option1: 'Apis',
					option2: 'Coleoptera',
					option3: 'Formicidae',
					option4: 'Rhopalocera',
					answer: 'Rhopalocera',
				},
				{
					quizNumber: '2',
					image: '',
					question: 'How hot is the surface of the sun?',
					option1: '1,233 K',
					option2: '5,778 K',
					option3: '12,130 K',
					option4: 'Waynetta',
					answer: '12,130 K',
				},
				{
					quizNumber: '3',
					image: '',
					question: 'How many times have Liverpool been relegated from the top flight of English football?',
					option1: 'Four',
					option2: 'Three',
					option3: 'Two',
					option4: 'Five',
					answer: 'Three',
				},
			],
		},
	],
};
